feat: Support Private CA for server certificates.
GoogleCloudPlatform/cloud-sql-jdbc-socket-factory pull request #2095
Opened 2024-12-17 20:00 UTC by hessjcg

2025-01-09 14:25 UTC, jackwotherspoon requested changes

2025-01-09 14:25 UTC, jackwotherspoon commented on core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
> +            isCasManagedCertificate(instanceMetadata),
Would it simplify things to have this function take in `serverCaMode` instead of `instanceMetadata`?

Would make adding a standalone unit test for `isCasManagedCertificate` easy and reduce having to call `.getServerCaMode()` twice in the function.

```suggestion
            isCasManagedCertificate(instanceMetadata.getServerCaMode()),
```

2025-01-09 17:13 UTC, hessjcg commented on core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
> +            isCasManagedCertificate(instanceMetadata),
I've inverted the logic here. Going forward, both GOOGLE_MANAGED_CAS_CA, CUSTOMER_MANAGED_CAS_CA, and future new kinds of CA we will do standard TLS domain name validation using the server certificate SAN records. The certificate validation logic for the original `GOOGLE_MANAGED_INTERNAL_CA` is now the exception. The code should reflect it: 

We don't have a unit test for this method, but this change is covered by this test: `com.google.cloud.sql.core.ConnectorTest#create_successfulPublicCasConnection`

2025-01-09 18:57 UTC, jackwotherspoon commented on core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
> +            isCasManagedCertificate(instanceMetadata),
I still think it would be simpler for the function to take in `serverCaMode` instead of `instanceMetadata`...

2025-01-10 17:10 UTC, hessjcg commented on core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
> +            isCasManagedCertificate(instanceMetadata),
Fixed.

2025-01-10 18:06 UTC, hessjcg commented on core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
> +  }
Good catch. Updated again for clarity.

2025-01-10 21:17 UTC, jackwotherspoon approved these changes
LGTM ✅

2025-01-10 21:22 UTC, merged