Mssql r2dbc
GoogleCloudPlatform/cloud-sql-jdbc-socket-factory pull request #328
Opened 2020-10-21 22:12 UTC by dmitry-s

## Change Description

Add MS Sql Server support

## Checklist

- [x] Make sure to open an issue as a 
  [bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
  before writing your code!  That way we can discuss the change, evaluate 
  designs, and agree on the general idea.
- [ ] Ensure the tests and linter pass
- [ ] Appropriate documentation is updated (if necessary)

## Relevant issues:

- Fixes #261

2020-10-22 14:09 UTC, dmitry-s commented
cc/ @meltsufin

2020-10-23 15:35 UTC, kurtisvg approved these changes
@shubha-rajan we should add a kokoro test on this before merging

2020-10-23 15:35 UTC, kurtisvg commented on r2dbc-mssql/pom.xml
> +          <version>0.8.5.BUILD-SNAPSHOT</version>
Does this require a SNAPSHOT version?

2020-10-23 19:11 UTC, shubha-rajan requested changes
I'd like to see tests passing before we merge. If we change the tests here to build the connection string using environment variables, Kokoro can run them.

2020-10-23 19:11 UTC, shubha-rajan commented on r2dbc-mssql/src/test/java/com/google/cloud/sql/core/R2dbcMssqlIntegrationTests.java
> +        ConnectionFactories.get(
We've updated our other tests to use a connection pool for testing. Can you update this as well? Also, if you use environment variables to build the connection string, we can check to see if the tests work with the CI before merging. See [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/r2dbc-mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIntegrationTests.java#L84) and [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/263/files#diff-aa701b353f647923b9fcf80435664101f904aa9dee087951795b5375fe2ceb59R48) for reference implementations

2020-10-27 03:43 UTC, shubha-rajan commented
@dmitry-s This looks ready to merge, however we'll have to hold off on merging this and #263 until we finalize the new naming pattern for connector artifacts.

2020-11-18 00:00 UTC, kurtisvg approved these changes

2020-11-18 22:13 UTC, shubha-rajan approved these changes

2020-11-18 22:47 UTC, merged