docs: Provide more information and pointers re. private IP connectivity in new Troubleshooting section in README
GoogleCloudPlatform/cloud-sql-jdbc-socket-factory pull request #376
Opened 2021-01-18 14:04 UTC by vorburger

## Relevant issues:

- Fixes #375

2021-01-20 20:52 UTC, shubha-rajan commented
Hi @vorburger, thanks for the pull request! I agree that a troubleshooting section might be useful for the README, but I'm not sure if including instructions on how to set up serverless VPC access is within the scope of the README for the Java Connector. @kurtisvg, what are your thoughts?

2021-01-20 20:55 UTC, vorburger commented
@shubha-rajan I've tried to link to appropriate places, more than provide directly much content here. If you guys strongly feel that it's still a bit excessive as is, it probably could be kept even more succinct, if that's a problem. Let me know if you need anything on particular to be removed.

2021-01-23 01:10 UTC, kurtisvg requested changes

2021-01-23 01:10 UTC, kurtisvg commented on README.md
> +If the Cloud SQL database instance is secured and does not have a public but only a private IP to connect to from within a Google Cloud hosted service, then additional configuration in Google Cloud (
This is a loaded statement. Having a public IP doesn't make the instance unsecure (and ultimately, having a private IP but not public doesn't make it secure).

2021-01-23 01:12 UTC, kurtisvg commented
> Hi @vorburger, thanks for the pull request! I agree that a troubleshooting section might be useful for the README, but I'm not sure if including instructions on how to set up serverless VPC access is within the scope of the README for the Java Connector. @kurtisvg, what are your thoughts?

I agree. It seems like it would be better to just have a link to the AppEngine docs. It does feel like we should explicitly state that this connector provides authorization and not connectivity (and what that means with effects to public vs private IP access) if we don't already.

2021-02-26 07:50 UTC, shubha-rajan commented
Hi @vorburger, we made some updates to the README in #409 that gives more info on private IP connectivity, so I'm going to close this PR for now. Please take a look and let us know if there's any other info you think is important to include. Thanks!

2021-02-26 07:50 UTC, closed without merging